# Generated by Django 5.2.3 on 2025-06-23 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("duration", models.DurationField(default=datetime.timedelta(0))),
                ("description", models.TextField()),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="tasks/pdfs/"),
                ),
                ("video_link", models.URLField(blank=True, null=True)),
                ("iscomplete", models.BooleanField(default=False)),
                ("inprogress", models.BooleanField(default=False)),
                ("isDone", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("inspirations", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
