# Generated by Django 5.2.3 on 2025-06-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="todays_score",
            field=models.IntegerField(default=0),
        ),
    ]
