# Generated by Django 5.2.3 on 2025-06-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_userscore_delete_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscore",
            name="last_updated_date",
            field=models.DateField(),
        ),
    ]
